### ISSUE TITLE
RTP input buffer too small

### ISSUE THREAD

**Issue by palaumarc** [ua-i2cat/liveMediaStreamer#4]
LiveMedia error shown if streams bitrate is too much larger. It can be fixed increasing size of H264 Frames (NALs) in the code (Types.hh)

**Comment by davidcassany** [comment]
Outdated, should be closed if it cannot be easily reproduced.

**Comment by palaumarc** [comment]
RTP input buffer set to a value defined in SourceManager (2MB). Included in release v0.2
