### ISSUE TITLE
dash mpd properly refresh 

### ISSUE THREAD

**Issue by gerardcl** [ua-i2cat/liveMediaStreamer#44]
at commit 9d215aff000de1488dcfe550bd851ee168768db0 :

- Player works only when initializing the dasher (player working when it starts playing on the initial window time of the dasher -when restarting testtranscoder with -dash flag). Does not seem a server cache problem.

- We should maintain a full version control of the whole scenario (player version, browser version, ...).
-- So, this issue is under "1.3" player version and "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36" browser version.

**Comment by palaumarc** [comment]
Resolved and included in release v0.2
