### ISSUE TITLE
testtranscoder with dash flag does not work with avmixer air output RTSP URI

### ISSUE THREAD

**Issue by gerardcl** [ua-i2cat/liveMediaStreamer#46]
at commit 9d215aff000de1488dcfe550bd851ee168768db0 :

- Cases:

 -- dash testtranscoder with development avmixer air output URI does NOT run dash process

 -- dash testtranscoder with master avmixer air output URI runs dash process

NOT WORKING WORKFLOW
Started playing session...
INFO  [Utils.cpp:487] - RTSP client session created! 
ERROR [Utils.cpp:473] - The queue is empty 
ERROR [Utils.cpp:473] - Connecting path head to first filter! 
INFO  [Utils.cpp:487] - Master reader: 3000 
INFO  [Utils.cpp:487] - Slave reader: 3001 
ERROR [Utils.cpp:473] - Error adding segmenter: reader does not exist 
ERROR [Utils.cpp:473] - Error adding segmenter 
ERROR [Utils.cpp:473] - Error setting bitrate. Provided id does not exist 
ERROR [Utils.cpp:473] - Error setting bitrate to segmenter 
INFO  [Utils.cpp:487] - Video path created from port 59566 

WORKING WORKFLOW
Started playing session...
INFO  [Utils.cpp:487] - RTSP client session created! 
INFO  [Utils.cpp:487] - Master reader: 3000 
INFO  [Utils.cpp:487] - Slave reader: 3001 
INFO  [Utils.cpp:487] - Video path created from port 38574 
ERROR [Utils.cpp:473] - The queue is empty 
ERROR [Utils.cpp:473] - Connecting path head to first filter! 
ERROR [Utils.cpp:473] - Error adding segmenter: reader does not exist 
ERROR [Utils.cpp:473] - Error adding segmenter 
INFO  [Utils.cpp:487] - Audio path created from port 0

**Comment by xcarol** [comment]
In general terms to solve a bug is an enhancement ;)
We would like to differentiate here what is a malfunction of an existing feature (bug) and a new feature that still doesn't exist (enhancement).

**Comment by gerardcl** [comment]
agree!

**Comment by palaumarc** [comment]
Resolved and included in master branch
