### ISSUE TITLE
dash segmenter should clean old segments that are not going to be used (e.g.: if restarting)

### ISSUE THREAD

**Issue by gerardcl** [ua-i2cat/liveMediaStreamer#48]
issue found at commit: ac867c1f9d9ce22add3a08d34f4374f30c68ac8a

- last session segments' folder is not cleaned when restarting the player (segments and init files)

**Comment by davidcassany** [comment]
I don't this is a desired feature, unless we add a folder management criteria. We should not delete anything contained in a folder we have not created IMHO.

**Comment by gerardcl** [comment]
Ok, we decided to open this issue in order to manage avoiding problems when restarting same dasher session. I agree that we should add a folder criteria or a file name per session convention too.
I'm closing this issue.
