### ISSUE TITLE
MP3 not working from LMS output to LMS input

### ISSUE THREAD

**Issue by gerardcl** [ua-i2cat/liveMediaStreamer#52]
issue found at commit fae513250bc7d3d58d4667fe4bcf0ada10ea34a5

- test done with LMS standard output with h264 and MP3; ffplay/vlc can playback RTSP but not testtranscoder, it loads decoder but is not able to decode properly. Seems an SDP issue (may we require adding extra info for MP3 audio as done for H264 video?)

- SDP from RTSP working to LMS input wiht h264 and MP3 streams (from VLC RTSP server):
v=0
o=- 15635096012114027085 15635096012114027085 IN IP4 gerardcl-VAYO
s=Unnamed
i=N/A
c=IN IP4 0.0.0.0
t=0 0
a=tool:vlc 2.1.6
a=recvonly
a=type:broadcast
a=charset:UTF-8
a=control:rtsp://127.0.0.1:8558/testVLC
m=audio 0 RTP/AVP 14
b=AS:128
b=RR:0
a=rtpmap:14 MPA/90000/2
a=control:rtsp://127.0.0.1:8554/testVLC/trackID=0
m=video 0 RTP/AVP 96
b=RR:0
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=64000d;sprop-parameter-sets=Z2QADayyAoP2HCAAAAMAIAAABkHihUk=,aOvDyyLA;
a=control:rtsp://127.0.0.1:8554/testVLC/trackID=1

- SDP from RTSP not working to LMS input wiht h264 and MP3 streams (from LMS RTSP server):
v=0
o=- 1431337628785268 1 IN IP4 147.83.206.83
s=
i=
t=0 0
a=tool:LIVE555 Streaming Media v2015.04.16
a=type:broadcast
a=control:*
a=range:npt=0-
a=x-qt-text-nam:
a=x-qt-text-inf:
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:2000
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=42C028;sprop-parameter-sets=Z0LAKNoB4AiflhAAAAMAEAAAAwMo8YMq,aM4PyA==
a=control:track1
m=audio 0 RTP/AVP 14
c=IN IP4 0.0.0.0
b=AS:192
a=control:track2

**Comment by palaumarc** [comment]
Not fixed, very specific case
