### ISSUE TITLE
SharedMemory unit test not compiling

### ISSUE THREAD

**Issue by palaumarc** [ua-i2cat/liveMediaStreamer#53]
SharedMemory unit test is ignored in Makefile.am because it crashes when compiling.

**Comment by xcarol** [comment]
It shouldn't be ignored, it should be corrected... ;)

**Comment by gerardcl** [comment]
now is corrected, unit test working. Right now improving its functional
test.

--------------------
  Gerard C.L.
--------------------

2015-05-13 12:22 GMT+02:00 Xavier Carol <notifications@github.com>:

**Comment by xcarol** [comment]
Great! Please close the issue.
